### ISSUE TITLE
Tracking issue for local storage

### ISSUE THREAD

**Issue by JBorrow** [simonsobs/librarian#9]
Starting this tracking issue as we try to remove the `ssh` requirement from wherever possible in Librarian to make things NERSC-etc. friendly.

@plaplant: It is my understanding that all Stores must be accessible over SSH. All inter-Librarian communication occurs from Store-Store (not Librarian to Librarian?). At the site, we have the Store url as `localhost`, so we ssh into ourselves and in theory launch globus transfers from there.

I would like to sub-class `BaseStore` to create `LocalStore` where all file operations are _local_ (i.e. basically remove `_ssh_slurp`).

A couple of quick questions: are my assertions right, and if so is there a reason that all Stores must be remote? Why is there no current option for local storage at the position that the Librarian server actually lives?

**Comment by JBorrow** [comment]
I think there is a more general issue here, and this part of the code could use a little refactoring.

There are essentially a few ways that we want to interact with the store:

- Librarian server <-> database, knowing what stores exist.
- Librarian server -> store for management (e.g. moving staged files, checking for free space).
- Client -> store for uploading data.

At the moment this is all essentially bundled up into the `BaseStore` class (later subclassed into `Store`, but that really just adds in the database ORM). Hence the `BaseStore` class makes a couple of tricky of assumptions about the way that stores should be interacted with:

- It assumes that the Store is a POSIX filesystem
- It assumes that all commands must/may be executed over SSH
- It assumes that all storage commands are synchronous (and makes those that are not synchronous be so; how does SneakerNet work?)

and also means that any transfer protocols must be implemented as methods on the class.

This is tricky because:

- SO:UK may not have a POSIX filesystem available
- Installing openssh-server and using it (even for local storage, i.e. ssh-ing into our own machine) might be tricky at some centers

Perhaps it makes sense to refactor into something that looks close to the following peseudocode, taking advantage of dependency injection. We want to abstract away the concept of a store and a transfer (which is not really currently the case because of its monolithic nature). At the moment the globus destination endpoint ID is stored in the config, not by the host librarian server, for instance.

```python
# Running on librarian server
class StoreMetadata(db.Model)
  """ Core metadata for store management (e.g. hostname, globus endpoint ID, etc.) """
  ... Stuff that registers the store in the Librarian database

class CoreStoreManager:
  """ Prototype for store management (e.g. moving staged files, finding storage). """
  def move(from, to):
    ...

class POSIXStoreManager:
  """ Example of a store manager that is 'used' by the librarian server """
  def move(from, to):
    ... ssh self.ssh_host; mv from to

class LocalPOSIXStoreManager:
  """ ... another manager """
  def move(from, to):
    ... os.move(from, to)


# Running on the client
class TransferManager:
  """ Prototype for transfer management """
  def transfer(local_path, remote_path=None):
    """ Remote path can be pre-staged """
    ...

class RsyncTransferManager:
  """ Example of a transfer manager using rysnc """
  def __init__(self, host_name, ...):
    self.host_name = host_name

  def transfer(local_path, remote_path=None):
     ... rsync loac_path self.host_name:remote_path

class GlobusTransferManager:
  """ Example of a transfer manager using globus """
  def __init__(self, destination_endpoint_id, ...);
    self.destination_endpoint_id = destination_endpoint_id

  def transfer(local_path, remote_path=None):
    ... globus_sdk.initiate_transfer(local_path, remote_path)...
```

This would allow a flow as follows:

```python
# Server
stores = StoreMetadata(...)

best_store = stores.find_store_with_available(bytes=...)
staging_location = best_store.stage(bytes=...)

best_store.post_transfer_information(staging_location, ...)
best_store.process_staged_file(...)

# Client
client = LibrarianClient(...)

transfer_manager = client.get_store_for(bytes=...)

transfer_manager.transfer(local_path)
```

In this way the transfer (e.g. globus, rsync, cp for local transfers, etc) is completely transparent.

**Comment by JBorrow** [comment]
Playing around with some ideas in https://github.com/JBorrow/librarian/tree/local-storage

**Comment by JBorrow** [comment]
An additional request that we have is to add timeouts for various librarian services so they do not hang.

**Comment by plaplant** [comment]
@JBorrow thanks for pushing on this! Yes, I think you're right about the assumptions/assertions that the Librarian makes. It is true that the Librarian assumes a POSIX filesystem, and many of the data-movement commands are essentially hard-coded to assume a Linux-like environment. (For example, figuring out how much storage is available is done over SSH and assumes `df` behaves as the `coreutils` version in terms of options.)

I think that your proposed refactor is a good one, especially given that SO:UK sounds like it is not a POSIX filesystem and will need site-specific handling of file routing and transfer to/from that site.

I think it might be most efficient to chat offline about how best to implement these changes. Thanks again for your help!

**Comment by JBorrow** [comment]
@plaplant Excellent, maybe it makes sense to meet some time early in the new year? I have been making lots of changes to the librarian in that linked branch... Maybe too many... Hopefully by the time we meet I will have a working full prototype. When I started changing the underlying ssh-based architechture, it made sense to make a few other changes, too.

**Comment by JBorrow** [comment]
Completed and ongoing tasks:

- [x] Move from Flask to FastAPI for inter-server communciation
- [x] Change background tasks to use a simpler framework
- [x] Use a completely separate thread for background tasks
- [x] Local store support
- [x] Full SQLite support
- [ ] Non-local store support
- [x] Local transfer support (wrapper for `cp`)
- [ ] Non-local transfer support (globus, rsync) 
- [x] Local clone background tasks (a local store cloning to another local store)
- [x] Remote clone between librarians (send)
- [ ] Remote clone between librarians (recv)
- [ ] Fallback when database communications fail
- [ ] Authentication
- [ ] Source and destination only mode for librarian instances
- [ ] Web frontend
- [ ] Communication with SO logging and flagging framework
- [ ] Unit testing
- [ ] Integration testing
- [ ] Docker support
- [ ] K8s support
- [ ] Deployment

**Comment by JBorrow** [comment]
I'm checking out on this project until the new year, but when I get back I will start by integration testing a bunch of stuff (primarily shares between librarians).

**Comment by JBorrow** [comment]
Development is coming along. I noticed that unfortunately the previous librarian server had close to zero test coverage, so that's a lot more work from scratch than I had anticipated. I have quite a nice test framework now where we spin up real test servers using pytest fixtures for testing the client, and thankfully the new FastAPI based endpoints are easy to unit test.

**Comment by JBorrow** [comment]
Coverage is coming up:

```
Module	statements	missing	excluded	coverage
[hera_librarian/base_store.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_669947648d7ae970_base_store_py.html)	174	174	0	0%
[hera_librarian/cli.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_669947648d7ae970_cli_py.html)	469	469	0	0%
[hera_librarian/models/stores.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_20f25aaae30c4430_stores_py.html)	3	3	0	0%
[hera_librarian/tests/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_40311fad220bd6aa___init___py.html)	9	9	0	0%
[hera_librarian/tests/test_base_store.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_40311fad220bd6aa_test_base_store_py.html)	108	108	0	0%
[hera_librarian/tests/test_cli.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_40311fad220bd6aa_test_cli_py.html)	82	82	0	0%
[hera_librarian/tests/test_utils.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_40311fad220bd6aa_test_utils_py.html)	86	86	0	0%
[librarian_background/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67___init___py.html)	15	15	0	0%
[librarian_background/bad.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_bad_py.html)	5	5	0	0%
[librarian_background/check_integrity.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_check_integrity_py.html)	43	43	0	0%
[librarian_background/core.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_core_py.html)	17	17	0	0%
[librarian_background/create_clone.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_create_clone_py.html)	86	86	0	0%
[librarian_background/poll.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_poll_py.html)	6	6	0	0%
[librarian_background/recieve_clone.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_recieve_clone_py.html)	44	44	0	0%
[librarian_background/send_clone.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_send_clone_py.html)	91	91	0	0%
[librarian_background/task.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_21cced45dfd52d67_task_py.html)	13	13	0	0%
[librarian_server/api/util.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_981e0548099b982b_util_py.html)	32	32	0	0%
[librarian_server/search.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_search_py.html)	647	647	0	0%
[librarian_server/store.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_store_py.html)	297	297	0	0%
[librarian_server/webutil.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_webutil_py.html)	207	181	0	13%
[hera_librarian/utils.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_669947648d7ae970_utils_py.html)	184	147	0	20%
[hera_librarian/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_669947648d7ae970___init___py.html)	162	79	0	51%
[librarian_server/orm/librarian.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983_librarian_py.html)	34	11	0	68%
[hera_librarian/transfers/core.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_4aba97608afe8b86_core_py.html)	7	2	0	71%
[librarian_server/stores/core.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_24a59d40b29dfcb9_core_py.html)	36	9	0	75%
[librarian_server/orm/transfer.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983_transfer_py.html)	132	23	0	83%
[librarian_server/stores/local.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_24a59d40b29dfcb9_local_py.html)	70	12	0	83%
[librarian_server/orm/storemetadata.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983_storemetadata_py.html)	100	13	0	87%
[librarian_server/api/upload.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_981e0548099b982b_upload_py.html)	87	7	0	92%
[librarian_server/deletion.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_deletion_py.html)	14	1	0	93%
[librarian_server/api/clone.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_981e0548099b982b_clone_py.html)	108	3	0	97%
[librarian_server/orm/file.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983_file_py.html)	31	1	0	97%
[librarian_server/settings.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_settings_py.html)	35	1	0	97%
[librarian_server/orm/instance.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983_instance_py.html)	49	1	0	98%
[hera_librarian/models/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_20f25aaae30c4430___init___py.html)	0	0	0	100%
[hera_librarian/models/clone.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_20f25aaae30c4430_clone_py.html)	82	0	0	100%
[hera_librarian/models/ping.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_20f25aaae30c4430_ping_py.html)	9	0	0	100%
[hera_librarian/models/uploads.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_20f25aaae30c4430_uploads_py.html)	61	0	0	100%
[hera_librarian/transfers/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_4aba97608afe8b86___init___py.html)	6	0	0	100%
[hera_librarian/transfers/local.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_4aba97608afe8b86_local_py.html)	14	0	0	100%
[librarian_server/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb___init___py.html)	13	0	0	100%
[librarian_server/api/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_981e0548099b982b___init___py.html)	3	0	0	100%
[librarian_server/api/ping.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_981e0548099b982b_ping_py.html)	11	0	0	100%
[librarian_server/database.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_database_py.html)	13	0	0	100%
[librarian_server/logger.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d7cd63bb5742a7bb_logger_py.html)	5	0	0	100%
[librarian_server/orm/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_d4af161ce263b983___init___py.html)	5	0	0	100%
[librarian_server/stores/__init__.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_24a59d40b29dfcb9___init___py.html)	6	0	0	100%
[librarian_server/stores/pathinfo.py](file:///Users/borrow-adm/Documents/SimonsObs/librarian/htmlcov/d_24a59d40b29dfcb9_pathinfo_py.html)	13	0	0	100%
Total	3724	2718	0	27%
```

**Comment by JBorrow** [comment]
Coverage only appears so low because of a lack of tests for old deprecated code. The new api endpoints are close to 100% coverage, and the new client also has very high coverage. The background tests will be getting implemented soon.

**Comment by JBorrow** [comment]
I am closing this issue as we work towards the _Deployment_ milestone.
